######################################################################
# Automatically generated by qmake (3.0) Sun Apr 3 10:02:46 2016
######################################################################

TEMPLATE = app
TARGET = proxy
INCLUDEPATH += .

QT += network
QT += concurrent

WORK_DIR = qt-build

UI_DIR = $$WORK_DIR
MOC_DIR = $$WORK_DIR
OBJECTS_DIR = $$WORK_DIR
RCC_DIR = $$WORK_DIR

# Input
HEADERS += proxy.h
SOURCES += main.cpp proxy.cpp
